language: python
pycharm:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.3"
  - "1.4"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"
# command to install dependencies
pip install --upgrade -r requirements.txt
# command to run tests
script: pytest